import { Color } from '../../board/map/tiles/Color'

export const Items = {
    Empty: [[Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ],
        [Color.LightGrey ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightGrey ],
        [Color.LightGrey ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightGrey ],
        [Color.LightGrey ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightGrey ],
        [Color.LightGrey ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightGrey ],
        [Color.LightGrey ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightGrey ],
        [Color.LightGrey ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightGrey ],
        [Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ],],
    Coffee: [[0               ,0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ],
            [0               ,0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
            [0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,0               ,0               ,0               ],
            [0               ,0               ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ],
            [0               ,0               ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ,0               ,Color.Grey  ],
            [0               ,0               ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ,0               ,Color.Grey  ],
            [0               ,0               ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ],
            [0               ,0               ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ,0               ,0               ],],
    Coin: [[0               ,0               ,0               ,Color.Yellow    ,Color.Yellow    ,0               ,0               ,0               ],
            [0               ,0               ,Color.Yellow    ,Color.Orange    ,Color.Yellow    ,Color.Yellow    ,0               ,0               ],
            [0               ,Color.Yellow    ,Color.Orange    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,0               ],
            [0               ,Color.Yellow    ,Color.Orange    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,0               ],
            [0               ,Color.Yellow    ,Color.Orange    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,0               ],
            [0               ,Color.Yellow    ,Color.Orange    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,0               ],
            [0               ,0               ,Color.Yellow    ,Color.Orange    ,Color.Yellow    ,Color.Yellow    ,0               ,0               ],
            [0               ,0               ,0               ,Color.Yellow    ,Color.Yellow    ,0               ,0               ,0               ],],
    BronzeDagger: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
                [0               ,0               ,0               ,0               ,Color.LightBrown     ,0               ,0               ,0               ],
                [0               ,0               ,0               ,Color.LightBrown     ,Color.LightBrown     ,0               ,0               ,0               ],
                [0               ,0               ,0               ,Color.LightBrown     ,Color.LightBrown     ,0               ,0               ,0               ],
                [0               ,0               ,0               ,Color.LightBrown     ,Color.LightBrown     ,0               ,0               ,0               ],
                [0               ,0               ,0               ,Color.LightBrown     ,Color.LightBrown     ,0               ,0               ,0               ],
                [0               ,0               ,Color.Grey  ,Color.Grey  ,Color.Grey  ,Color.Grey  ,0               ,0               ],
                [0               ,0               ,0               ,Color.LightBrown     ,Color.LightBrown     ,0               ,0               ,0               ],],
}
