import { Color } from './Color'

export const Tiles = {
    Tree: [[0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen2,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen2],
	[0               ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],],
    SmallTree: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
	[0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ],
	[0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ],
	[0               ,0               ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],],
    FlatGrass: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green    ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
    Grass: [[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green4, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green4, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green4, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green4, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],],
    Grass2: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
	Grass3: [[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
    TallGrass: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ],
    [Color.Green     ,Color.DarkGreen ,Color.Green     ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.Green     ,Color.Green     ],],
    TallGrass2: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green     ],],
	TallGrass3: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green4    ],
	[Color.Green     ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.Green     ],],
    Bush: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.DarkGreen ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.DarkGreen ,Color.Green4    ,Color.Green4    ,Color.Green     ],
	[Color.DarkGreen ,Color.Green4    ,Color.DarkGreen ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.DarkGreen ,Color.Green     ],
	[Color.Green     ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.Green     ,Color.Green     ],],
    DirtLeft: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green2    ,Color.Green,Color.Green],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green2    ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green2    ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],],
    DirtRight: [[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green2    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green2    ,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green2    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.LightBrown,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
    DirtUp: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green2    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green2    ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green2    ],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],],
    DirtDown: [[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
    Dirt: [[Color.Green,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green],],
    Rocks: [[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Grey, Color.Green, Color.Green],
	[Color.Green, Color.Grey, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Grey, Color.Green, Color.Green, Color.Grey, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],],
    Rocks2: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Grey      ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Grey      ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
}
