import { Color } from './Color'
export const SolidTiles = {
		Tree: [[0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen2,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen2],
	[0               ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],],
    SmallTree: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
	[0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ],
	[0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ],
	[0               ,0               ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],],
		River: [[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],],
  	River2: [[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.LightBlue ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.LightBlue ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],],
  	River3: [[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.LightBlue ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],
	[Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ,Color.Blue      ],],
		FenceV: [[0               ,0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ],
	[0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
	[0               ,0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
	[0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ],
	[0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
	[0               ,0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ],
	[0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
	[0               ,0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ],],
  	FenceH: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,Color.DarkGreen ,Color.DarkGreen ,0               ,Color.DarkGreen ,0               ,Color.DarkGreen ,0               ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[0               ,Color.DarkGreen ,0               ,Color.DarkGreen ,Color.DarkGreen ,0               ,Color.DarkGreen ,0               ],
	[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],],
  	FenceC: [[0               ,0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ],
	[0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[0               ,0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,0               ,Color.DarkGreen ,0               ],
	[0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ],],
	GnomeHouse: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.DarkGreen2,Color.DarkGreen2,0               ,0               ,0               ],
	[0               ,0               ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ,0               ],
	[0               ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ],
	[Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.Brown     ,Color.Brown     ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2],
	[Color.DarkGreen2,Color.DarkGreen2,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen2,Color.DarkGreen2],
	[0               ,Color.Brown     ,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Brown     ,0               ],
	[0               ,Color.Brown     ,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Brown     ,0               ],],
  	Wood: [[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],],
  	Leaves: [[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.Green4    ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.Green4    ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.Green4    ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],
	[Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ],],
		VillageHouse: [[0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.Brown     ,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Brown     ,Color.LightBrown],
	[Color.LightBrown,Color.Brown     ,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Brown     ,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Brown     ,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Brown     ,Color.LightBrown],],
		PlainTree: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ],
	[Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ],
	[Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ],
	[0               ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ],
	[0               ,0               ,0               ,Color.LightBrown,Color.LightBrown,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.LightBrown,Color.LightBrown,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.LightBrown,Color.LightBrown,0               ,0               ,0               ],],
  	SmallPlainTree: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
	[0               ,0               ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ,0               ],
	[0               ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ],
	[0               ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ],
	[0               ,0               ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ,0               ],
	[0               ,0               ,0               ,Color.LightBrown,Color.LightBrown,0               ,0               ,0               ],
	[0               ,0               ,0               ,Color.LightBrown,Color.LightBrown,0               ,0               ,0               ],],
}
export const Tiles = {
    FlatGrass: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green    ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
    Grass: [[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green4, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green4, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green4, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green4, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],],
    Grass2: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
		Grass3: [[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
    TallGrass: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ],
    [Color.Green     ,Color.DarkGreen ,Color.Green     ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.Green     ,Color.Green     ],],
    TallGrass2: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green     ],],
		TallGrass3: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ],
	[Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green4    ],
	[Color.Green     ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.Green     ],],
    Bush: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green4    ,Color.DarkGreen ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green     ,Color.Green     ],
	[Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.DarkGreen ,Color.Green4    ,Color.Green4    ,Color.Green     ],
	[Color.DarkGreen ,Color.Green4    ,Color.DarkGreen ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.DarkGreen ,Color.Green     ],
	[Color.Green     ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.Green     ,Color.Green     ],],
    DirtLeft: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green2    ,Color.Green,Color.Green],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green2    ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green2    ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],],
    DirtRight: [[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green2    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green2    ,Color.Green     ],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green2    ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.LightBrown,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
    DirtUp: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green2    ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green2    ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green2    ],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],],
    DirtDown: [[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
    Dirt: [[Color.Green,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
	[Color.Green,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Green],],
    Rocks: [[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Grey, Color.Green, Color.Green],
	[Color.Green, Color.Grey, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Grey, Color.Green, Color.Green, Color.Grey, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],
	[Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green, Color.Green],],
    Rocks2: [[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Grey      ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Grey      ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],
	[Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ,Color.Green     ],],
		PlainFlatGrass: [[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],],
  	PlainGrass: [[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],],
  	PlainGrass2: [[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],],
  	PlainTallGrass: [[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.Green     ,Color.Green     ,Color.LightGreen6,Color.Green     ,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.Green2    ,Color.Green2    ,Color.Green2    ,Color.Green2    ,Color.LightGreen6,Color.LightGreen6],],
  	PlainTallGrass2: [[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.LightGreen6],
	[Color.LightGreen6,Color.Green     ,Color.LightGreen6,Color.Green     ,Color.Green     ,Color.LightGreen6,Color.LightGreen6,Color.Green     ],
	[Color.LightGreen6,Color.LightGreen6,Color.Green     ,Color.Green     ,Color.Green     ,Color.LightGreen6,Color.Green     ,Color.LightGreen6],],
}
