import { Items, Quests, RewardType, StepType } from "../../../../../Enums.ts"
import QuestBase from "../../questBase.ts"
import StepBase from "../../stepBase.ts"
import SacredFireSword from "../../../../items/sacredFireSword.ts"
import SacredStone from "../../../../items/sacredStone.ts"
import { ItemsToHaveBase } from "../../itemsToHaveBase.ts"

export default class TheSacredStone extends QuestBase {
    constructor() {
        super(Quests.TheSacredStone,
            [
                new StepBase(StepType.NpcToTalk,[],'francis',
                    [
                        '...',
                        'My name is Francis Darci',
                        'What do you need?',
                        '...',
                        'Ediog sent you in search for something?',
                        'A stone??',
                        'I can\'t believe it, why would he want',
                        'some stupid stone',
                        '...',
                        'If you want any information from me',
                        'You\'ll have to help me',
                        'I\'m sick, and I\'ll probably die',
                        'Unless I have Cactus Juice',
                        'it is a rare drink that Cursed Cactus monsters',
                        'can drop. You\'ll find them in the desert.',
                        'I need 3 doses of that',
                        'now stay away from me.',
                        ' ',
                    ],[],0),
                new StepBase(StepType.ItemsToHave,[],'francis', [],
                    [
                        new ItemsToHaveBase(Items.CactusJuice, 3)
                    ],0),
                new StepBase(StepType.NpcToTalk,[],'francis',
                    [
                        'You actually found 3 doses',
                        'I cannot, I... This is',
                        'H-how? Why would you do this?',
                        'You just saved my life',
                        'Look, I think you\'re someone worthy',
                        'of knowing what I have',
                        'But first, I need to know',
                        'exactly what the mages know',
                        'go back to Ediog and ask him',
                        'what does he know about the stone',
                        'then come back and tell me',
                        ' ',
                    ],[],0),
                new StepBase(StepType.NpcToTalk,[],'ediog',
                    [
                        'Hello there! did you get the stone?',
                        'Francis Darci?',
                        'hmmm...',
                        'This has to stay between us',
                        'Well, the Sacred Stone is',
                        'a powerful relic',
                        'We believe it took a crucial part',
                        'into opening the portal',
                        'that brought evil creatures to this land',
                        'our researches show that the rock',
                        'came from space',
                        'and some ancient evil wizards found it',
                        'and used it to summon and open the portal',
                        'the stone could be the key to close it',
                        'that\'s what we know',
                        'I don\'t understand',
                        'how nor why could Francis have it',
                        'we have to get it...',
                        'go back to him and report all this',
                        'Oh, I didn\'t mention something',
                        'the sacred stone curses anyone carrying it',
                        'when they\'re too weak',
                        'that\'s probably why Francis was sick',
                        'only remains from a cursed creature can heal',
                        'from the curse, that\'s why Cactus Juice',
                        'saved Francis. So be careful!',
                        '-only level 50 or more can carry the stone-',
                        ' ',
                    ],[],0),
                new StepBase(StepType.NpcToTalk,[],'francis',
                    [
                        'So...',
                        'He said some ancient evil wizards found it?',
                        'Well he is right, but don\'t be alarmed',
                        'Me and my family have nothing to do',
                        'with dark magic. I have the stone',
                        'because my ancestors fought the wizards',
                        'at the Great Wizards War, back in 5419',
                        'almost 600 years ago',
                        'My friend, this stone means more to me',
                        'than anything in the world',
                        'but if it is needed to restore peace',
                        'I only ask for recognition',
                        'may people know Francis Darci was a part of it',
                        'here, take the stone!',
                        ' ',
                    ],[],0),
                new StepBase(StepType.LevelToReach,[],'francis', [],[],50),
                new StepBase(StepType.ItemsToReceive,[], 'francis', [],[],0,
                    [
                        new SacredStone(0)
                    ]),
                new StepBase(StepType.ItemsToHave,[],'ediog', [],
                    [
                        new ItemsToHaveBase(Items.SacredStone, 1)
                    ],0),
                new StepBase(StepType.NpcToTalk,[],'ediog',
                    [
                        'I can\'t believe my eyes',
                        'The Sacred Stone!',
                        'This will be remembered, hero',
                        'And yes, Francis Collaboration',
                        'will be forever engraved',
                        'in Tiny Land\'s history!',
                        'in appreciation for you work',
                        'I\'ll use my magic to canalize',
                        'some of the power of the stone',
                        'to a Fire Sword!',
                        'bring me a fire sword to make it sacred',
                        'For what I know, only dog-like demons',
                        'carry Fire Swords... You might have to kill some!',
                        'it will be hard',
                        'but the reward will be worth it!',
                        ' ',
                    ],[],0),
                new StepBase(StepType.ItemsToHave,[],'ediog', [],
                    [
                        new ItemsToHaveBase(Items.FireSword, 1)
                    ],0),
                new StepBase(StepType.NpcToTalk,[],'ediog',
                    [
                        '-you see Ediog saying some words-',
                        '-a weird aura comes out of the stone-',
                        '-the aura enters the sword-',
                        'Here you go, hero',
                        'thanks for everything!',
                        'we will be researching over the stone',
                        'may someday Tiny Land be a safe place again!',
                        '-you received 1500 xp!-',
                        '-you received Sacred Fire Sword!-',
                    ],[],0),
            ],
            RewardType.Both,
            new SacredFireSword(0),
            1500,
            'Hi there, hero! The mages are busy researching the stone!')
    }
}