import { Color } from '../board/map/tiles/Color'

export const Npcs = {
    Dog: [
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [Color.Brown, 0, 0, 0, 0, Color.Brown, 0, Color.Brown],
        [Color.Brown, 0, 0, 0, 0, Color.Brown, Color.Brown, Color.Brown],
        [0, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown],
        [0, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, 0, 0],
        [0, Color.Brown, 0, 0, 0, Color.Brown, 0, 0],
        [0, Color.Brown, 0, 0, 0, Color.Brown, 0, 0],
    ],
    Chicken: [[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,0 ,0 ,Color.DarkRed   ,Color.DarkRed   ,0 ,0 ],
        [0 ,0 ,0 ,0 ,Color.White2    ,Color.White2    ,0 ,0 ],
        [0 ,Color.White2    ,0 ,0 ,Color.White2    ,Color.White2    ,Color.Yellow    ,0 ],
        [0 ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.DarkRed   ,0 ],
        [0 ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0 ,0 ,0 ],
        [0 ,0 ,0 ,Color.LightYellow3,0 ,0 ,0 ,0 ],],
    Cow: [[0 ,0 ,0 ,0 ,0 ,Color.White2    ,0 ,0 ],
        [0 ,0 ,0 ,0 ,0 ,Color.White2    ,Color.White2    ,Color.LightYellow],
        [0 ,0 ,0 ,0 ,0 ,Color.Black     ,Color.White2    ,Color.LightYellow],
        [0 ,Color.Black     ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0 ],
        [Color.White2    ,Color.White2    ,Color.White2    ,Color.Black     ,Color.White2    ,Color.Black     ,Color.Black     ,0 ],
        [Color.White2    ,Color.White2    ,Color.White2    ,Color.Black     ,Color.White2    ,Color.Black     ,Color.White2    ,0 ],
        [0 ,Color.White2    ,Color.LightYellow,Color.LightYellow,0 ,Color.White2    ,0 ,0 ],
        [0 ,Color.Black     ,0 ,0 ,0 ,Color.Black     ,0 ,0 ],],
    Horse: [[0 ,0 ,0 ,0 ,0 ,Color.Brown     ,0 ,0 ],
        [0 ,0 ,0 ,0 ,0 ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
        [0 ,0 ,0 ,0 ,0 ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
        [0 ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0 ],
        [Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0 ],
        [Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0 ],
        [Color.Brown     ,Color.Brown     ,0 ,0 ,0 ,0 ,Color.Brown     ,0 ],
        [0 ,Color.Brown     ,0 ,0 ,0 ,0 ,Color.Brown     ,0 ],],
    Horse2: [[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0 ],
        [Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
        [Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ],
        [Color.Brown     ,Color.Brown     ,0 ,0 ,Color.Brown     ,0 ,Color.Brown     ,Color.Brown     ],
        [0 ,Color.Brown     ,0 ,0 ,Color.Brown     ,0 ,Color.Brown     ,0 ],],
    Camel: [[0 ,0 ,0 ,0 ,0 ,0 ,Color.DarkYellow,0 ],
        [0 ,0 ,Color.DarkYellow,Color.Yellow    ,Color.Yellow    ,0 ,Color.DarkYellow,Color.DarkYellow],
        [0 ,Color.DarkYellow,Color.DarkYellow,Color.Yellow    ,Color.LightBrown,Color.Yellow    ,Color.DarkYellow,0 ],
        [Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.LightBrown,Color.LightBrown,0 ],
        [Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,0 ],
        [0 ,Color.DarkYellow,0 ,0 ,0 ,Color.DarkYellow,0 ,0 ],
        [0 ,Color.DarkYellow,0 ,0 ,0 ,Color.DarkYellow,0 ,0 ],
        [0 ,Color.DarkYellow,0 ,0 ,0 ,Color.DarkYellow,0 ,0 ],],
    Spider: [
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, Color.Black, Color.Black, Color.Black, Color.Black, 0, 0],
        [0, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, 0],
        [0, Color.Black, Color.DarkPink2, Color.Black, Color.Black, Color.DarkPink2, Color.Black, 0],
        [Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black],
        [Color.Black, 0, Color.Black, 0, 0, Color.Black, 0, Color.Black],
        [Color.Black, 0, Color.Black, 0, 0, Color.Black, 0, Color.Black],
    ],
    ImpMeelee: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.DarkOrange,Color.Black     ,Color.DarkOrange,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [Color.Black     ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,0               ,Color.Black     ,0               ,0               ,Color.Black     ,0               ,0               ],],
    ImpArcher: [[0               ,0               ,0               ,0               ,0               ,0               ,Color.LightBrown,0               ],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.DarkOrange,Color.Black     ,Color.DarkOrange,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [Color.Black     ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.LightBrown],
        [Color.LightBrown,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [Color.LightBrown,0               ,Color.Black     ,0               ,0               ,Color.Black     ,Color.LightBrown,0               ],],
    ImpMage: [[0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,0               ,Color.Black     ],
        [0               ,0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Wine      ,Color.Yellow    ,Color.Black     ,Color.Yellow    ,0               ,Color.LightBrown],
        [Color.Black     ,0               ,Color.Wine      ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.LightBrown],
        [0               ,0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],],
    Slime: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,0               ,0               ],
        [0               ,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.White     ,Color.LightGreen2,0               ],
        [Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2],
        [Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2],
        [Color.LightGreen2,Color.LightGreen2,Color.DarkGreenBlue,Color.LightGreen2,Color.LightGreen2,Color.DarkGreenBlue,Color.LightGreen2,Color.LightGreen2],
        [Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2],
        [0               ,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,0               ],],
    Bee: [[Color.White2    ,Color.White2    ,0               ,0               ,0               ,0               ,Color.White2    ,Color.White2    ],
        [Color.White2    ,Color.White2    ,0               ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.LightYellow2,Color.White2    ],
        [0               ,Color.White2    ,Color.DarkGrey  ,Color.Black     ,Color.Black     ,Color.DarkGrey  ,Color.DarkGrey  ,0               ],
        [0               ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Black     ,0               ],
        [0               ,Color.DarkRed   ,Color.DarkYellow,Color.DarkYellow,Color.DarkRed   ,Color.Yellow    ,0               ,0               ],
        [0               ,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],],
    Witch: [[0               ,0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ],
        [0               ,0               ,Color.Black     ,Color.Yellow    ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [0               ,0               ,Color.Yellow    ,Color.Black     ,Color.Yellow    ,Color.Black     ,0               ,0               ],
        [Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ],
        [0               ,0               ,Color.DarkRed   ,Color.DarkGrey  ,Color.DarkRed   ,Color.DarkGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ],],
    Goblin: [[Color.LightBrown,0               ,Color.Grey      ,0               ,Color.Grey      ,0               ,0               ,0               ],
        [Color.LightBrown,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,0               ,Color.Red       ,Color.DarkGreen ,Color.Red       ,Color.DarkGreen ,0               ,0               ],
        [Color.DarkGreen ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,Color.DarkGreen ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ,0               ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,0               ,0               ,Color.DarkGreen ,0               ,0               ],],
    Goblin2: [[0               ,0               ,0               ,Color.Grey      ,0               ,Color.Grey      ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.DarkRed   ,Color.DarkGreen ,Color.DarkRed   ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,Color.DarkGreen ],
        [0               ,Color.DarkGreen ,Color.DarkGreen ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [Color.DarkGreen ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,0               ,0               ,Color.DarkGreen ,0               ,0               ],],
    Goblin3: [[0               ,0               ,Color.Grey      ,0               ,0               ,Color.Grey      ,0               ,0               ],
        [Color.LightBrown,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,0               ,Color.DarkRed   ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkRed   ,0               ,0               ],
        [Color.LightBrown,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,Color.DarkGreen ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [Color.DarkGreen ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,Color.DarkGreen ],
        [Color.LightBrown,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,0               ,0               ,Color.DarkGreen ,0               ,0               ],],
    Ligneus: [[0               ,Color.DarkGreen ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [0               ,0               ,Color.DarkOrange,Color.Brown     ,Color.Brown     ,Color.DarkOrange,0               ,0               ],
        [0               ,Color.DarkGreen ,Color.Brown     ,Color.Black     ,Color.Black     ,Color.Brown     ,0               ,Color.DarkGreen ],
        [Color.Brown     ,0               ,Color.Brown     ,Color.Black     ,Color.Black     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ],
        [Color.DarkGreen ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,Color.Brown     ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [0               ,Color.Brown     ,Color.DarkGreen ,0               ,0               ,0               ,Color.Brown     ,0               ],],
    Skeleton: [[0               ,0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ],
        [0               ,0               ,0               ,Color.LightGrey ,Color.Black     ,Color.LightGrey ,Color.Black     ,0               ],
        [0               ,Color.LightGrey ,Color.DarkGrey  ,Color.DarkGrey  ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ],
        [Color.LightGrey ,0               ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,0               ,Color.LightGrey ],
        [0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,0               ,0               ,0               ],
        [0               ,0               ,Color.Grey      ,Color.Grey      ,Color.Grey      ,Color.Grey      ,0               ,0               ],
        [0               ,0               ,Color.Grey      ,0               ,0               ,Color.Grey      ,0               ,0               ],],
    SkeletonKnight: [[0               ,0               ,Color.DarkGrey  ,0               ,0               ,Color.DarkGrey  ,0               ,Color.DarkGrey  ],
        [0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ,Color.DarkGrey  ],
        [0               ,0               ,Color.LightGrey ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.DarkGrey  ],
        [0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.Black     ,Color.LightGrey ,0               ,Color.DarkGrey  ],
        [0               ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ],
        [0               ,Color.DarkGrey  ,Color.LightGrey ,Color.DarkGrey  ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,0               ,Color.LightGrey ,0               ,0               ,Color.LightGrey ,0               ,0               ],],
    Rat: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,Color.LightOrange,0               ,0               ,Color.LightOrange,0               ],
        [0               ,0               ,0               ,Color.DarkGreenBlue,Color.DarkRed   ,Color.DarkGreenBlue,Color.DarkRed   ,0               ],
        [Color.LightOrange,0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.LightOrange],
        [Color.LightOrange,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ],
        [0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ,0               ],
        [0               ,Color.LightOrange,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.LightOrange,0               ,0               ,0               ],],
    ButterFlew: [[0               ,0               ,0               ,0               ,Color.DarkPink2 ,Color.DarkPink2 ,Color.DarkPink2 ,0               ],
        [Color.LightRed  ,0               ,0               ,Color.DarkPink2 ,Color.DarkPink2 ,Color.Pink3     ,Color.DarkPink2 ,Color.DarkPink2 ],
        [0               ,Color.LightRed  ,0               ,Color.DarkPink2 ,Color.Pink3     ,Color.DarkPink  ,Color.Pink3     ,Color.DarkPink2 ],
        [Color.DarkPink  ,Color.LightPurple2,Color.DarkPink2 ,Color.DarkPink2 ,Color.DarkPink  ,Color.Pink3     ,Color.DarkPink  ,Color.DarkPink2 ],
        [Color.LightPurple2,Color.LightPurple2,Color.DarkPink2 ,Color.DarkPink2 ,Color.Pink3     ,Color.DarkPink  ,Color.Pink3     ,Color.DarkPink2 ],
        [0               ,Color.LightPurple2,Color.LightPurple2,Color.DarkPink2 ,Color.DarkPink2 ,Color.Pink3     ,Color.DarkPink  ,Color.DarkPink2 ],
        [0               ,0               ,Color.LightPurple2,Color.LightPurple2,Color.DarkPink2 ,Color.DarkPink2 ,Color.DarkPink2 ,Color.DarkPink2 ],
        [0               ,0               ,0               ,Color.LightPurple2,Color.LightPurple2,0               ,0               ,0               ],],
    GrassSnake: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [Color.Black     ,Color.DarkGreen ,0               ,0               ,0               ,0               ,0               ,0               ],
        [Color.DarkGreen ,Color.DarkGreen ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,Color.DarkGreen ,0               ,0               ,0               ,0               ,0               ,Color.DarkGreen ],
        [0               ,Color.DarkGreen ,0               ,0               ,0               ,0               ,Color.DarkGreen ,0               ],
        [0               ,0               ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ,0               ],
        [0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ],
        [Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2],],
    Document: [[0               ,0               ,0               ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ],
        [0               ,0               ,Color.White2    ,Color.Black     ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.Black     ,Color.White2    ,Color.White2    ],
        [Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ],
        [Color.White2    ,Color.White2    ,Color.Grey      ,Color.Grey      ,Color.White2    ,Color.White2    ,Color.White2    ,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.Grey      ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,0               ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ,0               ],],
    EvilEye: [[0               ,0               ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ],
        [Color.White2    ,Color.White2    ,Color.White2    ,Color.Black     ,Color.White     ,Color.White2    ,Color.White2    ,0               ],
        [Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,0               ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],],
    WaterBlob: [[0               ,0               ,0               ,Color.Purple    ,Color.Purple    ,Color.Purple    ,0               ,0               ],
        [0               ,0               ,0               ,Color.DarkOrange,Color.Purple    ,Color.DarkOrange,0               ,0               ],
        [0               ,0               ,0               ,Color.Purple    ,Color.Purple    ,Color.Purple    ,0               ,0               ],
        [0               ,0               ,0               ,Color.Blue2     ,Color.DarkBlue  ,0               ,0               ,0               ],
        [0               ,0               ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.Purple    ,Color.DarkPurple,0               ,0               ],
        [0               ,0               ,Color.DarkBlue  ,Color.Purple    ,Color.LightPurple2,Color.DarkBlue2 ,0               ,0               ],
        [0               ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.LightPurple2,Color.DarkPurple,Color.DarkBlue  ,Color.Blue2     ,0               ],
        [Color.DarkBlue2 ,Color.LightPurple2,Color.DarkBlue  ,Color.DarkPurple,Color.Purple    ,Color.LightPurple2,Color.DarkBlue2 ,Color.DarkPurple],],
    Ogre: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ,0               ],
        [Color.LightGreen4,Color.LightGreen4,Color.LightGreen4,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [Color.Black     ,Color.LightGreen4,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ],
        [Color.LightGreen4,Color.LightGreen4,Color.LightGreen4,Color.Brown     ,Color.Brown     ,Color.LightGreen4,Color.Brown     ,0               ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.LightGreen4,Color.Brown     ,0               ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ],
        [0               ,0               ,0               ,Color.LightGreen4,0               ,Color.LightGreen4,0               ,0               ],],
    AdamantGhost: [[0               ,0               ,Color.DarkGreenBlue,0               ,0               ,Color.DarkGreenBlue,0               ,0               ],
        [Color.GreenBlue3,0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ],
        [Color.GreenBlue3,0               ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkGreenBlue,0               ,0               ],
        [Color.GreenBlue3,0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ],
        [Color.GreenBlue3,Color.DarkGreenBlue,Color.GreenBlue3,Color.GreenBlue3,Color.GreenBlue3,Color.Grey      ,Color.Grey      ,Color.Grey      ],
        [Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.Grey      ,Color.DarkGrey  ,Color.Grey      ],
        [Color.GreenBlue3,0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.Grey      ,Color.Grey      ,Color.Grey      ],
        [0               ,0               ,Color.DarkGreenBlue,0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ],],
    FireBlob: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,Color.DarkOrange,0               ],
        [0               ,0               ,0               ,Color.DarkOrange,Color.Orange    ,Color.DarkOrange,0               ,0               ],
        [0               ,0               ,Color.DarkOrange,Color.Orange    ,Color.DarkOrange,Color.DarkOrange,0               ,0               ],
        [0               ,Color.Orange    ,Color.DarkOrange,Color.Black     ,Color.Orange    ,Color.DarkOrange,Color.DarkOrange,0               ],
        [0               ,Color.DarkOrange,Color.Orange    ,Color.Black     ,Color.Orange    ,Color.Black     ,Color.Orange    ,0               ],
        [Color.Orange    ,Color.DarkOrange,Color.DarkOrange,Color.Orange    ,Color.DarkOrange,Color.Orange    ,Color.DarkOrange,Color.Orange    ],],
    SandCat: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [Color.LightBrown,0               ,Color.LightBrown,0               ,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ],
        [Color.Brown     ,Color.LightBrown,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
        [Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
        [0               ,0               ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
        [0               ,Color.LightBrown,0               ,0               ,0               ,0               ,Color.LightBrown,0               ],],
    SandSnake: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [Color.Black     ,Color.Yellow    ,0               ,0               ,0               ,0               ,0               ,0               ],
        [Color.Yellow    ,Color.Yellow    ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,Color.Yellow    ,0               ,0               ,0               ,0               ,0               ,Color.Yellow    ],
        [0               ,Color.Yellow    ,0               ,0               ,0               ,0               ,Color.Yellow    ,0               ],
        [0               ,0               ,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,0               ,0               ],
        [0               ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,0               ],
        [Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow],],
    Zombie: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.LightYellow,Color.LightYellow,0               ,0               ],
        [0               ,0               ,Color.Black     ,Color.DarkGreen ,Color.Black     ,Color.DarkGreen ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [0               ,Color.Green4    ,Color.Green4    ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.Green4    ,Color.Green4    ,0               ],
        [0               ,0               ,0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ],
        [0               ,0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ],
        [0               ,0               ,0               ,Color.DarkGreen ,0               ,0               ,Color.DarkGreen ,0               ],],
    CursedCactus: [[0               ,0               ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ,0               ,0               ],
        [Color.DarkGreen ,0               ,Color.DarkPink  ,Color.Green4    ,Color.DarkPink  ,0               ,0               ,0               ],
        [Color.Green4    ,0               ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ,0               ,0               ],
        [Color.Green4    ,Color.Green4    ,Color.DarkGreen ,Color.Green4    ,Color.DarkGreen2,0               ,Color.DarkGreen2,0               ],
        [Color.DarkGreen2,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.Green4    ,0               ,Color.Green4    ,0               ],
        [0               ,0               ,Color.DarkGreen2,Color.Green4    ,Color.DarkGreen ,Color.Green4    ,Color.Green4    ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.Green4    ,Color.Green4    ,Color.Green4    ,Color.DarkGreen ,0               ],
        [0               ,0               ,Color.Green4    ,Color.Green4    ,Color.DarkGreen ,0               ,0               ,0               ],],
    SandSpirit: [[Color.Yellow    ,0               ,0               ,0               ,0               ,0               ,0               ,Color.Yellow    ],
        [0               ,Color.Yellow    ,Color.Yellow    ,Color.DarkYellow,Color.DarkYellow,Color.Yellow    ,Color.Yellow    ,0               ],
        [0               ,Color.Yellow    ,Color.DarkYellow,Color.Yellow    ,Color.Yellow    ,Color.DarkYellow,Color.Yellow    ,0               ],
        [0               ,Color.DarkYellow,Color.Brown     ,Color.Yellow    ,Color.Yellow    ,Color.Brown     ,Color.DarkYellow,0               ],
        [Color.DarkYellow,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.DarkYellow],
        [0               ,Color.DarkYellow,Color.DarkYellow,Color.Yellow    ,Color.Yellow    ,Color.DarkYellow,Color.DarkYellow,0               ],
        [0               ,0               ,Color.DarkYellow,Color.Yellow    ,Color.Yellow    ,Color.DarkYellow,0               ,0               ],
        [0               ,0               ,0               ,Color.DarkYellow,Color.DarkYellow,0               ,0               ,0               ],],
    SandTotem: [[0               ,0               ,Color.LightBrown,Color.Orange    ,Color.Orange    ,Color.LightBrown,0               ,0               ],
        [0               ,Color.Orange    ,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Orange    ,0               ],
        [Color.LightBrown,Color.Orange    ,Color.LightBrown,Color.Brown     ,Color.Brown     ,Color.LightBrown,Color.Orange    ,Color.LightBrown],
        [0               ,Color.Orange    ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Orange    ,0               ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [Color.Orange    ,Color.LightBrown,Color.LightBrown,Color.Orange    ,Color.Orange    ,Color.LightBrown,Color.LightBrown,Color.Orange    ],
        [Color.LightBrown,Color.Orange    ,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Orange    ,Color.LightBrown],
        [0               ,0               ,Color.LightBrown,Color.Orange    ,Color.Orange    ,Color.LightBrown,0               ,0               ],],
    Demon: [[0               ,0               ,Color.DarkRed   ,0               ,0               ,Color.DarkRed   ,0               ,0               ],
        [Color.Wine      ,0               ,Color.DarkRed   ,Color.Black     ,Color.DarkRed   ,Color.Black     ,0               ,Color.Wine      ],
        [Color.Wine      ,Color.Wine      ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.Wine      ,Color.Wine      ],
        [Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.DarkRed   ,Color.DarkRed   ,Color.Wine      ,Color.Wine      ,Color.Wine      ],
        [Color.Wine      ,Color.Wine      ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.Wine      ,Color.Wine      ],
        [Color.Wine      ,0               ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,0               ,Color.Wine      ],
        [Color.Wine      ,0               ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,0               ,Color.Wine      ],
        [0               ,0               ,Color.DarkRed   ,0               ,0               ,Color.DarkRed   ,0               ,0               ],],
    Demon2: [[0               ,0               ,0               ,0               ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ],
        [0               ,0               ,0               ,0               ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,0               ],
        [Color.DarkRed   ,0               ,Color.DarkRed   ,0               ,Color.DarkRed   ,Color.DarkRed   ,0               ,0               ],
        [Color.Black     ,Color.DarkRed   ,Color.Black     ,Color.Wine      ,Color.DarkRed   ,0               ,0               ,0               ],
        [Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.Wine      ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.Wine      ],
        [0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.Wine      ],
        [0               ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.DarkRed   ,Color.Wine      ],
        [0               ,Color.DarkRed   ,0               ,0               ,0               ,0               ,Color.DarkRed   ,0               ],],
    Zero: [[0 ,0 ,0 ,Color.LightGrey  ,Color.LightGrey  ,0 ,0 ,0 ],
        [0 ,0 ,0 ,Color.LightGrey  ,Color.LightGrey  ,0 ,0 ,0 ],
        [0 ,0 ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0 ,0 ],
        [0 ,0 ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0 ,0 ],
        [0 ,0 ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0 ,0 ],
        [0 ,0 ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0 ,0 ],
        [0 ,0 ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0 ,0 ],
        [0 ,0 ,Color.LightGrey  ,0 ,0 ,Color.LightGrey  ,0 ,0 ],],
    FemaleGnome: [[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,Color.LightYellow2,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.LightYellow2,0 ,0 ],
        [0 ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,0 ,0 ],
        [0 ,Color.Yellow    ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.Yellow    ,0 ,0 ],
        [0 ,Color.Green2    ,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.Green2    ,0 ,0 ],
        [0 ,Color.LightYellow2,Color.LightGreen6,Color.LightGreen6,Color.LightGreen6,Color.LightYellow2,0 ,0 ],
        [0 ,0 ,Color.LightYellow2,0 ,Color.LightYellow2,0 ,0 ,0 ],],
    MaleGnome: [[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,Color.LightYellow2,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.LightYellow2,0 ,0 ],
        [0 ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,0 ,0 ],
        [0 ,0 ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0 ,0 ,0 ],
        [0 ,Color.LightYellow2,Color.GreenBlue3,Color.GreenBlue3,Color.GreenBlue3,Color.LightYellow2,0 ,0 ],
        [0 ,0 ,Color.GreenBlue3,Color.GreenBlue3,Color.GreenBlue3,0 ,0 ,0 ],
        [0 ,0 ,Color.LightYellow2,0 ,Color.LightYellow2,0 ,0 ,0 ],],
    AncientGnome: [[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,Color.LightYellow2,Color.White2    ,Color.White2    ,Color.White2    ,Color.LightYellow2,0 ,0 ],
        [0 ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,0 ,0 ],
        [0 ,Color.Wine      ,Color.White2    ,Color.White2    ,Color.White2    ,Color.Wine      ,0 ,0 ],
        [0 ,Color.Wine      ,Color.DarkGreen2,Color.White2    ,Color.DarkGreen2,Color.Wine      ,0 ,0 ],
        [0 ,Color.Wine      ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.Wine      ,0 ,0 ],
        [0 ,0 ,Color.LightYellow2,0 ,Color.LightYellow2,0 ,0 ,0 ],],
    WhiteMaleFarmer: [[0 ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0 ,0 ],
        [0 ,Color.Black     ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,0 ,0 ],
        [0 ,Color.Black     ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0 ,Color.Brown     ],
        [0 ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0 ,Color.Brown     ],
        [Color.LightYellow,Color.Brown     ,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.LightYellow,Color.Brown     ],
        [Color.LightYellow,Color.Brown     ,Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.Brown     ,0 ,Color.LightYellow],
        [0 ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0 ,Color.Brown     ],
        [0 ,Color.DarkGreenBlue,Color.DarkGreenBlue,0 ,Color.DarkGreenBlue,Color.DarkGreenBlue,0 ,Color.Brown     ],],
    BlackMaleFarmer: [[0 ,0 ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0 ,0 ],
        [0 ,Color.Black     ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0 ,0 ],
        [0 ,Color.Black     ,Color.Brown     ,Color.Black     ,Color.Brown     ,Color.Black     ,0 ,Color.LightBrown],
        [0 ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0 ,Color.LightBrown],
        [Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.DarkGreen ,Color.DarkGreen ,Color.LightBrown,Color.Brown     ,Color.LightBrown],
        [Color.Brown     ,Color.LightBrown,Color.LightBrown,Color.DarkGreen ,Color.DarkGreen ,Color.LightBrown,0 ,Color.Brown     ],
        [0 ,Color.Orange    ,Color.Orange    ,Color.Orange    ,Color.Orange    ,Color.Orange    ,0 ,Color.LightBrown],
        [0 ,Color.Orange    ,Color.Orange    ,0 ,0 ,Color.Orange    ,0 ,Color.LightBrown],],
    WhiteFemaleFarmer: [[0 ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,0 ,0 ],
        [0 ,Color.Yellow    ,Color.Pink      ,Color.LightYellow,Color.LightYellow,Color.LightYellow,0 ,0 ],
        [0 ,Color.Yellow    ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0 ,0 ],
        [Color.Yellow    ,Color.Yellow    ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0 ,0 ],
        [Color.Yellow    ,Color.LightYellow,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow,0 ],
        [0 ,Color.LightYellow,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow,0 ],
        [0 ,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,0 ],
        [0 ,0 ,Color.LightYellow,0 ,0 ,Color.LightYellow,0 ,0 ],],
    BlackFemaleFarmer: [[0 ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,0 ,0 ],
        [0 ,Color.LightBrown,Color.Pink      ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0 ,0 ],
        [0 ,Color.LightBrown,Color.Brown     ,Color.Black     ,Color.Brown     ,Color.Black     ,0 ,0 ],
        [Color.LightBrown,Color.LightBrown,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0 ,0 ],
        [Color.LightBrown,Color.Brown     ,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.Brown     ,0 ],
        [0 ,Color.Brown     ,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.Brown     ,0 ],
        [0 ,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,Color.LightYellow3,0 ],
        [0 ,0 ,Color.Brown     ,0 ,0 ,Color.Brown     ,0 ,0 ],],
    OldMan: [[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0 ,Color.Brown     ],
        [0 ,0 ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.Black     ,0 ,Color.Brown     ],
        [0 ,Color.DarkPurple,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.DarkPurple,Color.Brown     ],
        [0 ,Color.DarkPurple,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.DarkPurple,Color.Brown     ],
        [0 ,Color.DarkPurple,Color.DarkPurple,Color.LightGrey ,Color.LightGrey ,Color.DarkPurple,Color.DarkPurple,Color.LightYellow],
        [0 ,0 ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.LightGrey ,Color.DarkGreenBlue,0 ,Color.Brown     ],
        [0 ,0 ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0 ,Color.Brown     ],],
    MytklashsFlower: [[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ],
        [0 ,0 ,Color.DarkPink  ,Color.DarkPink2 ,Color.DarkPink  ,Color.DarkPink2 ,Color.DarkPink  ,0 ],
        [0 ,0 ,0 ,Color.DarkPink  ,Color.DarkPink  ,Color.DarkPink  ,0 ,0 ],
        [0 ,0 ,0 ,0 ,Color.DarkPurple,0 ,0 ,0 ],
        [0 ,0 ,0 ,0 ,Color.Purple    ,0 ,0 ,0 ],
        [0 ,0 ,Color.DarkGreen ,0 ,Color.Purple    ,0 ,0 ,0 ],
        [0 ,0 ,0 ,Color.Purple    ,0 ,0 ,0 ,0 ],
        [0 ,0 ,0 ,Color.Purple    ,0 ,0 ,0 ,0 ],],
    Wizard1: [[0 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0 ,0 ,Color.Purple],
        [Color.DarkBlue2 ,0 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0 ,Color.DarkPurple],
        [0 ,Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,Color.Brown     ],
        [0 ,0 ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0 ,Color.Brown     ],
        [0 ,0 ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0 ,Color.Brown     ],
        [0 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.Blue4     ,Color.Blue4     ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.Brown     ],
        [0 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.Blue4     ,Color.DarkBlue2 ,0 ,Color.Brown     ],
        [0 ,0 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0 ,Color.Brown     ],],
    Wizard2: [[Color.DarkPink  ,0 ,0 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0 ],
        [Color.DarkPink2 ,0 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0 ,Color.DarkBlue2 ],
        [Color.Brown     ,Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,0 ],
        [Color.Brown     ,0 ,Color.Black     ,Color.LightYellow,Color.Black     ,Color.LightYellow,0 ,0 ],
        [Color.Brown     ,0 ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0 ,0 ],
        [Color.Brown     ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.Blue4     ,Color.Blue4     ,Color.DarkBlue2 ,Color.DarkBlue2 ,0 ],
        [Color.Brown     ,0 ,Color.DarkBlue2 ,Color.Blue4     ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0 ],
        [Color.Brown     ,0 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0 ,0 ],],
    Wizard3: [[0               ,0               ,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,0               ],
        [0               ,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,0               ,Color.DarkPurple],
        [Color.Purple    ,Color.Purple    ,Color.Purple    ,Color.Purple    ,Color.Purple    ,Color.DarkPurple,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Purple    ,Color.Purple    ,0               ],
        [Color.Brown     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ,0               ],
        [Color.Brown     ,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,0               ,0               ],
        [Color.LightYellow,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.LightYellow,0               ,0               ],
        [Color.Brown     ,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,0               ,0               ,0               ],],
    Merchant1: [[0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0               ,Color.Brown     ],
        [0               ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,Color.Brown     ],
        [Color.DarkGreenBlue,Color.Brown     ,Color.Brown     ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.Brown     ,Color.DarkGreenBlue,Color.Brown     ],
        [Color.LightYellow,Color.Brown     ,Color.Brown     ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.Brown     ,0               ,Color.LightYellow],
        [0               ,Color.Grey      ,Color.Grey      ,Color.Grey      ,Color.Grey      ,Color.Grey      ,0               ,Color.Brown     ],
        [0               ,Color.Grey      ,Color.Grey      ,0               ,0               ,Color.Grey      ,0               ,Color.Brown     ],],
    Merchant2: [[0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ],
        [Color.Blue3     ,Color.Blue3     ,Color.Blue3     ,Color.Blue3     ,Color.Blue3     ,Color.Blue3     ,Color.Blue3     ,0               ],
        [Color.LightYellow,Color.Blue3     ,Color.Blue3     ,Color.Blue3     ,Color.Blue3     ,Color.Blue3     ,Color.LightYellow,0               ],
        [0               ,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ,0               ],
        [0               ,Color.DarkGreen2,Color.DarkGreen2,0               ,0               ,Color.DarkGreen2,0               ,0               ],],
    CityMale1: [[0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0               ,0               ],
        [Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Blue3     ,Color.Blue3     ,Color.Brown     ,Color.Brown     ,0               ],
        [Color.LightYellow2,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Blue3     ,Color.Brown     ,Color.LightYellow2,0               ],
        [0               ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0               ,0               ],
        [0               ,Color.DarkBlue2 ,Color.DarkBlue2 ,0               ,0               ,Color.DarkBlue2 ,0               ,0               ],],
    CityMale2: [[0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0               ,0               ],
        [Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,0               ],
        [Color.LightYellow2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.DarkGreen2,Color.LightYellow2,0               ],
        [0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ],
        [0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ,Color.DarkGreenBlue,0               ,0               ],],
    CityMale3: [[0               ,0               ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ,0               ],
        [Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown],
        [0               ,Color.Black     ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0               ,0               ],
        [Color.LightYellow2,Color.GreenBlue3,Color.GreenBlue3,Color.Blue      ,Color.Blue      ,Color.GreenBlue3,Color.LightYellow2,0               ],
        [Color.LightYellow2,Color.GreenBlue3,Color.GreenBlue3,Color.Blue      ,Color.Blue      ,Color.GreenBlue3,Color.LightYellow2,0               ],
        [0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ],
        [0               ,Color.DarkGreenBlue,Color.DarkGreenBlue,0               ,0               ,Color.DarkGreenBlue,0               ,0               ],],
    CityMale4: [[0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Black     ,Color.Brown     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ],
        [Color.Brown     ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.Brown     ,0               ],
        [0               ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0               ,0               ],
        [0               ,Color.DarkBlue2 ,Color.DarkBlue2 ,0               ,0               ,Color.DarkBlue2 ,0               ,0               ],],
    CityMale5: [[0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Black     ,Color.Brown     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [Color.Blue4     ,Color.Blue4     ,Color.Blue4     ,Color.White2    ,Color.White2    ,Color.Blue4     ,Color.Blue4     ,0               ],
        [Color.Brown     ,Color.Blue4     ,Color.Blue4     ,Color.White2    ,Color.White2    ,Color.Blue4     ,Color.Brown     ,0               ],
        [0               ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ,0               ],
        [0               ,Color.LightBrown,Color.LightBrown,0               ,0               ,Color.LightBrown,0               ,0               ],],
    CityMale6: [[0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Black     ,Color.Brown     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [Color.Brown     ,Color.Orange    ,Color.Orange    ,Color.DarkGreen2,Color.DarkGreen2,Color.Orange    ,Color.Brown     ,0               ],
        [Color.Brown     ,Color.Orange    ,Color.Orange    ,Color.Orange    ,Color.DarkGreen2,Color.Orange    ,Color.Brown     ,0               ],
        [0               ,Color.DarkOrange,Color.DarkOrange,Color.DarkOrange,Color.DarkOrange,Color.DarkOrange,0               ,0               ],
        [0               ,Color.DarkOrange,Color.DarkOrange,0               ,0               ,Color.DarkOrange,0               ,0               ],],
    CityMale7: [[0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ],
        [0               ,Color.Blue4     ,Color.Wine      ,Color.Wine      ,Color.White2    ,Color.Wine      ,Color.Blue4     ,0               ],
        [0               ,Color.LightYellow,Color.Wine      ,Color.Wine      ,Color.White2    ,Color.Wine      ,Color.LightYellow,0               ],
        [0               ,0               ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,Color.DarkBlue2 ,0               ,0               ],
        [0               ,0               ,Color.DarkBlue2 ,Color.DarkBlue2 ,0               ,Color.DarkBlue2 ,0               ,0               ],],
    CityMale8: [[0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ,Color.Brown     ],
        [Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,Color.Brown     ,0               ],
        [Color.Black     ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0               ,Color.Brown     ,0               ],
        [Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,Color.Brown     ,0               ],
        [Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.Brown     ,0               ],
        [Color.LightYellow,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ,Color.LightYellow,0               ],
        [0               ,Color.DarkOrange,Color.DarkOrange,Color.DarkOrange,Color.DarkOrange,0               ,Color.Brown     ,0               ],
        [0               ,Color.DarkOrange,Color.DarkOrange,0               ,Color.DarkOrange,0               ,Color.Brown     ,0               ],],
    CityMale9: [[0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ,0               ],
        [Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ,0               ],
        [Color.Black     ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0               ,0               ,0               ],
        [Color.Black     ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ,0               ],
        [Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,0               ,0               ],
        [Color.LightYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.LightYellow,0               ,0               ],
        [0               ,Color.LightPurple,Color.LightPurple,Color.LightPurple,Color.LightPurple,0               ,0               ,0               ],
        [0               ,Color.LightPurple,Color.LightPurple,0               ,Color.LightPurple,0               ,0               ,0               ],],
    CityOldMale1: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,Color.LightGrey ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0               ,0               ],
        [0               ,Color.LightGrey ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,Color.Black     ,0               ,Color.LightBrown],
        [Color.LightYellow2,Color.White2    ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow,Color.LightBrown],
        [Color.LightYellow2,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,Color.LightYellow],
        [0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,Color.LightBrown],
        [0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,Color.Brown     ,0               ,Color.LightBrown],],
    CityOldMale2: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,0               ,0               ],
        [Color.LightGrey ,Color.LightYellow,Color.Black     ,Color.LightYellow,Color.Black     ,0               ,0               ,Color.Brown     ],
        [Color.LightGrey ,Color.LightYellow,Color.LightYellow,Color.LightYellow,Color.LightYellow,0               ,Color.Brown     ,0               ],
        [Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.Brown     ,0               ],
        [Color.LightYellow,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.DarkGreenBlue,Color.LightYellow,Color.LightYellow,0               ],
        [0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,Color.Brown     ,0               ],
        [0               ,Color.Brown     ,0               ,0               ,Color.Brown     ,0               ,Color.Brown     ,0               ],],
    CityFemale1: [[0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ],
        [0               ,Color.Black     ,Color.Black     ,Color.Pink2     ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0               ],
        [Color.Black     ,Color.Black     ,Color.Black     ,Color.LightYellow2,Color.Black     ,Color.LightYellow2,Color.Black     ,0               ],
        [Color.Black     ,Color.Black     ,Color.Black     ,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,Color.LightYellow2,0               ],
        [Color.Black     ,Color.LightYellow2,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.LightYellow2],
        [0               ,Color.LightYellow2,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.LightYellow2],
        [0               ,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow],
        [0               ,0               ,Color.LightYellow2,0               ,0               ,0               ,Color.LightYellow2,0               ],],
    CityFemale2: [[0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Pink3     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ,0               ],
        [0               ,Color.Black     ,Color.LightBrown,Color.Black     ,Color.LightBrown,Color.Black     ,0               ,0               ],
        [Color.Black     ,Color.Black     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ,0               ],
        [Color.Black     ,Color.LightBrown,Color.Pink      ,Color.Pink      ,Color.Pink      ,Color.Pink      ,Color.LightBrown,0               ],
        [0               ,Color.LightBrown,Color.Pink      ,Color.Pink      ,Color.Pink      ,Color.Pink      ,Color.LightBrown,0               ],
        [0               ,Color.Pink      ,Color.Pink      ,Color.Pink      ,Color.Pink      ,Color.Pink      ,Color.Pink      ,0               ],
        [0               ,0               ,Color.LightBrown,0               ,0               ,Color.LightBrown,0               ,0               ],],
    CityFemale3: [[0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,Color.Black     ,Color.LightOrange,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,Color.Black     ,Color.Brown     ,Color.Black     ,Color.Brown     ,Color.Black     ,0               ,0               ],
        [Color.Black     ,Color.Black     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,Color.Brown     ,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.Brown     ,0               ],
        [0               ,Color.Brown     ,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.Brown     ,0               ],
        [0               ,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,Color.DarkPurple,0               ],
        [0               ,0               ,Color.Brown     ,0               ,0               ,Color.Brown     ,0               ,0               ],],
    CityGuard: [[0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,Color.LightGrey ,Color.LightGrey ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.GreenBlue3],
        [0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.Black     ,Color.LightGrey ,0               ,Color.GreenBlue3],
        [0               ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,0               ,Color.GreenBlue3],
        [Color.GreenBlue3,Color.GreenBlue3,Color.GreenBlue3,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.GreenBlue3],
        [Color.GreenBlue3,Color.DarkGreenBlue,Color.GreenBlue3,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ,Color.Black     ],
        [Color.GreenBlue3,Color.GreenBlue3,Color.GreenBlue3,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,0               ,Color.GreenBlue3],
        [0               ,Color.LightGrey ,Color.LightGrey ,0               ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],],
    DesertMale1: [[0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,Color.White2    ,Color.LightBrown,Color.Black     ,Color.LightBrown,Color.Black     ,0               ,0               ],
        [0               ,Color.White2    ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ,0               ],
        [Color.LightBrown,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightBrown,0               ],
        [Color.LightBrown,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightBrown,0               ],
        [0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,Color.LightBrown,Color.LightBrown,0               ,0               ,Color.LightBrown,0               ,0               ],],
    DesertMale2: [[0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,Color.DarkOrange,Color.LightBrown,Color.Black     ,Color.LightBrown,Color.Black     ,0               ,0               ],
        [0               ,Color.DarkOrange,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ,0               ],
        [Color.LightBrown,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.LightBrown,0               ],
        [Color.LightBrown,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.LightBrown,0               ],
        [0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,Color.Brown     ,0               ,0               ],],
    DesertMale3: [[0               ,Color.White     ,Color.White     ,Color.White     ,Color.White     ,Color.White     ,0               ,0               ],
        [0               ,Color.White     ,Color.White     ,Color.White     ,Color.White     ,Color.White     ,0               ,0               ],
        [0               ,Color.White     ,Color.LightBrown,Color.Black     ,Color.LightBrown,Color.Black     ,0               ,0               ],
        [0               ,Color.White     ,Color.LightBrown,Color.LightBrown,Color.LightBrown,Color.LightBrown,0               ,0               ],
        [Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ],
        [Color.LightBrown,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.LightBrown,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],],
    DesertMale4: [[0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [0               ,Color.White2    ,Color.LightBrown,Color.Black     ,Color.LightBrown,Color.Black     ,0               ,0               ],
        [0               ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,Color.White2    ,0               ,0               ],
        [Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,0               ],
        [Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,Color.LightBlue ,0               ],
        [0               ,Color.LightPurple,Color.LightPurple,Color.LightPurple,Color.LightPurple,Color.LightPurple,0               ,0               ],
        [0               ,Color.LightPurple,Color.LightPurple,0               ,0               ,Color.LightPurple,0               ,0               ],],
} as any
