import { Color } from '../board/map/tiles/Color'

export const Npcs = {
    Dog: [
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [Color.Brown, 0, 0, 0, 0, Color.Brown, 0, Color.Brown],
        [Color.Brown, 0, 0, 0, 0, Color.Brown, Color.Brown, Color.Brown],
        [0, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown],
        [0, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, 0, 0],
        [0, Color.Brown, 0, 0, 0, Color.Brown, 0, 0],
        [0, Color.Brown, 0, 0, 0, Color.Brown, 0, 0],
    ],
    Spider: [
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, Color.Black, Color.Black, Color.Black, Color.Black, 0, 0],
        [0, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, 0],
        [0, Color.Black, Color.DarkPink2, Color.Black, Color.Black, Color.DarkPink2, Color.Black, 0],
        [Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black],
        [Color.Black, 0, Color.Black, 0, 0, Color.Black, 0, Color.Black],
        [Color.Black, 0, Color.Black, 0, 0, Color.Black, 0, Color.Black],
    ],
    ImpMeelee: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.DarkOrange,Color.Black     ,Color.DarkOrange,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [Color.Black     ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,0               ,Color.Black     ,0               ,0               ,Color.Black     ,0               ,0               ],],
    ImpArcher: [[0               ,0               ,0               ,0               ,0               ,0               ,Color.LightBrown,0               ],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.DarkOrange,Color.Black     ,Color.DarkOrange,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [Color.Black     ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.LightBrown],
        [Color.LightBrown,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [Color.LightBrown,0               ,Color.Black     ,0               ,0               ,Color.Black     ,Color.LightBrown,0               ],],
    ImpMage: [[0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,0               ,Color.Black     ],
        [0               ,0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Wine      ,Color.Yellow    ,Color.Black     ,Color.Yellow    ,0               ,Color.LightBrown],
        [Color.Black     ,0               ,Color.Wine      ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.LightBrown],
        [0               ,0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],],
    Slime: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,0               ,0               ],
        [0               ,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.White     ,Color.LightGreen2,0               ],
        [Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2],
        [Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2],
        [Color.LightGreen2,Color.LightGreen2,Color.DarkGreenBlue,Color.LightGreen2,Color.LightGreen2,Color.DarkGreenBlue,Color.LightGreen2,Color.LightGreen2],
        [Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2],
        [0               ,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,Color.LightGreen2,0               ],],
    Bee: [[Color.White2    ,Color.White2    ,0               ,0               ,0               ,0               ,Color.White2    ,Color.White2    ],
        [Color.White2    ,Color.White2    ,0               ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.LightYellow2,Color.White2    ],
        [0               ,Color.White2    ,Color.DarkGrey  ,Color.Black     ,Color.Black     ,Color.DarkGrey  ,Color.DarkGrey  ,0               ],
        [0               ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Yellow    ,Color.Black     ,0               ],
        [0               ,Color.DarkRed   ,Color.DarkYellow,Color.DarkYellow,Color.DarkRed   ,Color.Yellow    ,0               ,0               ],
        [0               ,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,Color.DarkYellow,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],
        [0               ,0               ,0               ,0               ,0               ,0               ,0               ,0               ],],
    Witch: [[0               ,0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ],
        [0               ,0               ,Color.Black     ,Color.Yellow    ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [0               ,0               ,Color.Yellow    ,Color.Black     ,Color.Yellow    ,Color.Black     ,0               ,0               ],
        [Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ],
        [0               ,0               ,Color.DarkRed   ,Color.DarkGrey  ,Color.DarkRed   ,Color.DarkGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ],],
    Goblin: [[Color.LightBrown,0               ,Color.Grey      ,0               ,Color.Grey      ,0               ,0               ,0               ],
        [Color.LightBrown,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,0               ,Color.Red       ,Color.DarkGreen ,Color.Red       ,Color.DarkGreen ,0               ,0               ],
        [Color.DarkGreen ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,Color.DarkGreen ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ,0               ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,0               ,0               ,Color.DarkGreen ,0               ,0               ],],
    Goblin2: [[0               ,0               ,0               ,Color.Grey      ,0               ,Color.Grey      ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.DarkRed   ,Color.DarkGreen ,Color.DarkRed   ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,Color.DarkGreen ],
        [0               ,Color.DarkGreen ,Color.DarkGreen ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [Color.DarkGreen ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,0               ,0               ,Color.DarkGreen ,0               ,0               ],],
    Goblin3: [[0               ,0               ,Color.Grey      ,0               ,0               ,Color.Grey      ,0               ,0               ],
        [Color.LightBrown,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,0               ,Color.DarkRed   ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkRed   ,0               ,0               ],
        [Color.LightBrown,0               ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,Color.DarkGreen ,0               ,0               ],
        [Color.LightBrown,Color.DarkGreen ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [Color.DarkGreen ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,Color.DarkGreen ],
        [Color.LightBrown,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ,0               ],
        [0               ,0               ,Color.DarkGreen ,0               ,0               ,Color.DarkGreen ,0               ,0               ],],
    Ligneus: [[0               ,Color.DarkGreen ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [0               ,0               ,Color.DarkOrange,Color.Brown     ,Color.Brown     ,Color.DarkOrange,0               ,0               ],
        [0               ,Color.DarkGreen ,Color.Brown     ,Color.Black     ,Color.Black     ,Color.Brown     ,0               ,Color.DarkGreen ],
        [Color.Brown     ,0               ,Color.Brown     ,Color.Black     ,Color.Black     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,0               ],
        [Color.DarkGreen ,0               ,0               ,Color.Brown     ,Color.Brown     ,0               ,0               ,Color.Brown     ],
        [0               ,0               ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.Brown     ,Color.DarkGreen ,0               ],
        [0               ,Color.Brown     ,Color.DarkGreen ,0               ,0               ,0               ,Color.Brown     ,0               ],],
    Skeleton: [[0               ,0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ],
        [0               ,0               ,0               ,Color.LightGrey ,Color.Black     ,Color.LightGrey ,Color.Black     ,0               ],
        [0               ,Color.LightGrey ,Color.DarkGrey  ,Color.DarkGrey  ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ],
        [Color.LightGrey ,0               ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,0               ,Color.LightGrey ],
        [0               ,0               ,0               ,Color.LightGrey ,Color.LightGrey ,0               ,0               ,0               ],
        [0               ,0               ,Color.Grey      ,Color.Grey      ,Color.Grey      ,Color.Grey      ,0               ,0               ],
        [0               ,0               ,Color.Grey      ,0               ,0               ,Color.Grey      ,0               ,0               ],],
    SkeletonKnight: [[0               ,0               ,Color.DarkGrey  ,0               ,0               ,Color.DarkGrey  ,0               ,Color.DarkGrey  ],
        [0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,0               ,Color.DarkGrey  ],
        [0               ,0               ,Color.LightGrey ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.DarkGrey  ],
        [0               ,0               ,Color.LightGrey ,Color.LightGrey ,Color.Black     ,Color.LightGrey ,0               ,Color.DarkGrey  ],
        [0               ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ,Color.LightGrey ],
        [0               ,Color.DarkGrey  ,Color.LightGrey ,Color.DarkGrey  ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,Color.DarkGrey  ,Color.DarkGrey  ,Color.DarkGrey  ,Color.LightGrey ,Color.LightGrey ,0               ,0               ],
        [0               ,0               ,Color.LightGrey ,0               ,0               ,Color.LightGrey ,0               ,0               ],],
    Zero: [[0               ,0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ,0               ],
        [0               ,0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,0               ,0               ,Color.LightGrey  ,0               ,0               ],],
} as any
