import { Color } from '../board/map/tiles/Color'

export const Npcs = {
    Dog: [
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [Color.Brown, 0, 0, 0, 0, Color.Brown, 0, Color.Brown],
        [Color.Brown, 0, 0, 0, 0, Color.Brown, Color.Brown, Color.Brown],
        [0, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown],
        [0, Color.Brown, Color.Brown, Color.Brown, Color.Brown, Color.Brown, 0, 0],
        [0, Color.Brown, 0, 0, 0, Color.Brown, 0, 0],
        [0, Color.Brown, 0, 0, 0, Color.Brown, 0, 0],
    ],
    Spider: [
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, Color.Black, Color.Black, Color.Black, Color.Black, 0, 0],
        [0, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, 0],
        [0, Color.Black, Color.DarkPink2, Color.Black, Color.Black, Color.DarkPink2, Color.Black, 0],
        [Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black, Color.Black],
        [Color.Black, 0, Color.Black, 0, 0, Color.Black, 0, Color.Black],
        [Color.Black, 0, Color.Black, 0, 0, Color.Black, 0, Color.Black],
    ],
    ImpMeelee: [[0               ,0               ,0               ,0               ,0               ,0               ,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.DarkOrange,Color.Black     ,Color.DarkOrange,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [Color.Black     ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ],
        [0               ,0               ,Color.Black     ,0               ,0               ,Color.Black     ,0               ,0               ],],
    ImpArcher: [[0               ,0               ,0               ,0               ,0               ,0               ,Color.LightBrown,0               ],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Black     ,Color.DarkOrange,Color.Black     ,Color.DarkOrange,0               ,Color.LightBrown],
        [0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [Color.Black     ,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,Color.LightBrown],
        [Color.LightBrown,0               ,Color.Black     ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.LightBrown],
        [Color.LightBrown,0               ,Color.Black     ,0               ,0               ,Color.Black     ,Color.LightBrown,0               ],],
    ImpMage: [[0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,0               ,Color.Black     ],
        [0               ,0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [0               ,0               ,Color.Wine      ,Color.Yellow    ,Color.Black     ,Color.Yellow    ,0               ,Color.LightBrown],
        [Color.Black     ,0               ,Color.Wine      ,Color.Black     ,Color.Black     ,Color.Black     ,0               ,Color.Black     ],
        [0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.LightBrown],
        [0               ,0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [0               ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],
        [Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,Color.Wine      ,0               ,Color.LightBrown],],
    Zero: [[0               ,0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ,0               ],
        [0               ,0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,Color.LightGrey  ,0               ,0               ],
        [0               ,0               ,Color.LightGrey  ,0               ,0               ,Color.LightGrey  ,0               ,0               ],],
} as any
