const Tiles = {
    "Tree": [[0             ,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,0              ],
            [Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen],
            [Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen],
            [Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen],
            [0              ,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,0              ],
            [0              ,0              ,0              ,Color.Brown    ,Color.Brown    ,0              ,0              ,0              ],
            [0              ,0              ,0              ,Color.Brown    ,Color.Brown    ,0              ,0              ,0              ],
            [0              ,0              ,0              ,Color.Brown    ,Color.Brown    ,0              ,0              ,0              ]],
    "SmallTree": [[0              ,0              ,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,0              ,0              ],
                  [0              ,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,0              ],
                  [0              ,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,0              ],
                  [0              ,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,0              ],
                  [0              ,0              ,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,0              ,0              ],
                  [0              ,0              ,0              ,Color.Brown    ,Color.Brown    ,0              ,0              ,0              ],
                  [0              ,0              ,0              ,Color.Brown    ,Color.Brown    ,0              ,0              ,0              ],
                  [0              ,0              ,0              ,Color.Brown    ,Color.Brown    ,0              ,0              ,0              ]],
    "FlatGrass": [[Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
                 [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
                 [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
                 [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
                 [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
                 [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
                 [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
                 [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green]],
    "Grass": [[Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
              [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.DarkGreen,Color.Green,Color.Green],
              [Color.Green,Color.Green,Color.DarkGreen,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
              [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
              [Color.Green,Color.DarkGreen,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
              [Color.Green,Color.Green,Color.Green,Color.Green,Color.DarkGreen,Color.Green,Color.Green,Color.Green],
              [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
              [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green]],
    "Bush": [[Color.Green           ,Color.Green              ,Color.Green              ,Color.Green    ,Color.Green    ,Color.Green    ,Color.Green    ,Color.Green     ],
             [Color.Green           ,Color.Green              ,Color.Green              ,Color.Green    ,Color.Green    ,Color.Green    ,Color.Green    ,Color.Green     ],
             [Color.Green           ,Color.Green              ,Color.Green              ,Color.Green    ,Color.Green    ,Color.Green    ,Color.Green    ,Color.DarkGreen ],
             [Color.Green           ,Color.Green              ,Color.DarkGreen          ,Color.Green    ,Color.Green    ,Color.Green    ,Color.DarkGreen,Color.Green     ],
             [Color.Green           ,Color.Green              ,Color.Green              ,Color.DarkGreen,Color.Green    ,Color.Green    ,Color.DarkGreen,Color.Green     ],
             [Color.Green           ,Color.Green              ,Color.Green              ,Color.DarkGreen,Color.Green    ,Color.DarkGreen,Color.Green    ,Color.Green     ],
             [Color.Green           ,Color.DarkGreen          ,Color.Green              ,Color.Green    ,Color.DarkGreen,Color.DarkGreen,Color.Green    ,Color.DarkGreen ],
             [Color.Green           ,Color.Green              ,Color.DarkGreen          ,Color.Green    ,Color.DarkGreen,Color.DarkGreen,Color.DarkGreen,Color.Green    ]],
    "Dirt": [[Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
             [Color.Green,Color.Green,Color.LightPeach,Color.LightPeach,Color.Green,Color.Green,Color.Green,Color.Green],
             [Color.Green,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.Green,Color.Green],
             [Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach],
             [Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach],
             [Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach],
             [Color.Green,Color.Green,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.LightPeach,Color.Green],
             [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green]],
    "Rocks": [[Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
             [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
             [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.DarkGrey,Color.Green,Color.Green],
             [Color.Green,Color.DarkGrey,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
             [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
             [Color.Green,Color.Green,Color.DarkGrey,Color.Green,Color.Green,Color.DarkGrey,Color.Green,Color.Green],
             [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green],
             [Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green,Color.Green]],
}